spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiap_ford_club
    username: fiap_ford_club
    password: fiap_ford_club
    driver-class-name: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1
  sql:
    init:
      mode: always
      username: fiap_ford_club
      password: fiap_ford_club
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          create-database-schemas: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true